---
name: Build and push image

on:
    push:
    pull_request:
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    SHOULD_PUSH: false

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Set env.SHOULD_PUSH based on branch and event
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: echo "SHOULD_PUSH=true" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: ${{ env.SHOULD_PUSH }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  file: Containerfile
                  github-token: ${{ secrets.GITHUB_TOKEN }}
